swagger: '2.0'
info:
  version: '1.0.0'
  title: Domain API
  description: This is a read-only API that returns the base domain of LivePerson that should be used in the APIs outlined in this document.

  contact:
    name: Liveperson
    email: support@liveperson.com
    url: http://liveperson.com
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: api.liveperson.net
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /{accountId}/service/{serviceName}/baseURI.json?version=1.0:
    get:
      description: Return the domain for a desired domain name
      operationId: domain for account
      produces:
        - application/json
        - application/xml
        - text/xml
        - text/html
      parameters:
        - name: accountId
          in: path
          description: accountId of the desired domain
          required: true
          type: string
        - name: serviceName
          in: path
          description: maximum number of results to return
          required: true
          type: string
          format: int32
      responses:
        '200':
          description: Domain response
          schema:
            type: array
            items:
              $ref: '#/definitions/domain'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
definitions:
  domain:
    type: object
    required:
      - service
      - account
      - baseURI
    properties:
      service:
        type: string
      account:
        type: string
      baseURI:
        type: string
  errorModel:
    type: object
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
